cmake_minimum_required(VERSION 3.28)
file(STRINGS "${REFERENCE}" REFERENCE_LINES)
file(STRINGS "${FACADE}" FACADE_LINES)
function(SIGNATURES INPUT OUTPUT)
	set(RESULT "")
	foreach(LINE IN LISTS ${INPUT})
		string(TOLOWER "${LINE}" LOWER)
		if(LOWER MATCHES "^([a-z]+ +)?(function|event) +[a-z_]+\\(")
			string(REGEX REPLACE "[ \t\r]" "" NORMALIZED "${LOWER}")
			list(APPEND RESULT "${NORMALIZED}")
		endif()
	endforeach()
	set(${OUTPUT} "${RESULT}" PARENT_SCOPE)
endfunction()
SIGNATURES(REFERENCE_LINES EXPECTED)
SIGNATURES(FACADE_LINES ACTUAL)
foreach(SIGNATURE IN LISTS EXPECTED)
	if(NOT SIGNATURE IN_LIST ACTUAL)
		message(FATAL_ERROR "Missing or changed SkyUI signature: ${SIGNATURE}")
	endif()
endforeach()
file(READ "${FACADE}" CONTENT)
get_filename_component(FACADE_NAME "${FACADE}" NAME)
if(FACADE_NAME STREQUAL "SKI_ConfigBase.psc")
	if(NOT CONTENT MATCHES "if !BridgeCanSelectOption\\(a_index\\)" OR
		NOT CONTENT MATCHES "Math.LogicalAnd\\(packed, 0x300\\) == 0")
		message(FATAL_ERROR "Direct selections must reject disabled and hidden rows before mod callbacks")
	endif()
	if(NOT CONTENT MATCHES "event OnBridgeRegistrationRequested")
		message(FATAL_ERROR "Missing asynchronous registration recovery handler")
	endif()
	string(REGEX MATCH "event OnGameReload\\(\\)[\r\n]+(.*)" RELOAD_TAIL "${CONTENT}")
	string(FIND "${RELOAD_TAIL}" "EndEvent" RELOAD_END)
	if(RELOAD_END LESS 0)
		message(FATAL_ERROR "Missing reload event")
	endif()
	string(SUBSTRING "${RELOAD_TAIL}" 0 ${RELOAD_END} RELOAD_BODY)
	if(RELOAD_BODY MATCHES "OnConfigManagerReady\\(" OR NOT RELOAD_BODY MATCHES "SendModEvent\\(registrationEvent\\)")
		message(FATAL_ERROR "Reload must queue registration instead of waiting for the manager")
	endif()
	if(NOT CONTENT MATCHES "a_sender != self" OR NOT CONTENT MATCHES "UnregisterForModEvent\\(a_eventName\\)")
		message(FATAL_ERROR "Registration recovery event must be scoped and one-shot")
	endif()
endif()
if(CONTENT MATCHES "UI\\.(Invoke|Set|Get)")
	message(FATAL_ERROR "Native facade must not dispatch to the Journal movie")
endif()
list(LENGTH EXPECTED COUNT)
if(NOT DEFINED MINIMUM)
	set(MINIMUM 100)
endif()
if(COUNT LESS MINIMUM)
	message(FATAL_ERROR "Incomplete reference contract")
endif()
message(STATUS "Verified ${COUNT} Classic function and event signatures")
