cmake_minimum_required(VERSION 3.28)
file(READ "${ROOT}/src/Papyrus/UIInvokeStringArrayBridge.cpp" UI_FORWARDING)
string(FIND "${UI_FORWARDING}" "tasks->AddUITask(" QUEUED_INVOKE)
string(FIND "${UI_FORWARDING}" "ui->GetMenu(menuName)" DEFERRED_MENU)
if(QUEUED_INVOKE EQUAL -1 OR DEFERRED_MENU EQUAL -1 OR DEFERRED_MENU LESS QUEUED_INVOKE)
	message(FATAL_ERROR "Scaleform forwarding must resolve the movie on the UI queue")
endif()
string(SUBSTRING "${UI_FORWARDING}" 0 ${QUEUED_INVOKE} BEFORE_UI_QUEUE)
if(BEFORE_UI_QUEUE MATCHES "IsMenuOpen|GetMenu|RE::UI::GetSingleton")
	message(FATAL_ERROR "Scaleform forwarding must not discard calls while an asynchronously opened menu is pending")
endif()
foreach(REQUIRED "if (!menu || !menu->uiMovie)" "menuName = std::move(a_menuName)" "buildValues = std::move(a_buildValues)" "auto values = buildValues(*menu->uiMovie)" "menu->uiMovie->InvokeNoReturn")
	string(FIND "${UI_FORWARDING}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing deferred Scaleform lifetime guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeHostMenuMode.cpp" MENU_MODE)
foreach(REQUIRED "TokenForOwner(reinterpret_cast<std::uintptr_t>(caller->self.GetObject().get()))" "caller->self.IsObject()" "original->GetParamCount() != 0" "GetIsLatent()" "replacement->GetReturnType() == original->GetReturnType()" "original.get())->MarshallAndDispatch")
	string(FIND "${MENU_MODE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing scoped native menu-mode guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeFacadeContract.cpp" LOADED_CONTRACT)
foreach(REQUIRED "type->GetMemberFuncIter()" "kLinkedValid" "BridgeEnterCall" "BridgeLeaveCall" "BridgeAwaitCall" "BridgePublishBuffers" "BridgeCallAdmissionContract" "function->GetParamCount() != parameters" "SamePapyrusIdentifier(type->GetName(), expectedType)" "SamePapyrusIdentifier(function->GetName().c_str(), name)")
	string(FIND "${LOADED_CONTRACT}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing loaded facade contract check: ${REQUIRED}")
	endif()
endforeach()
foreach(ADMISSION "Discovery/AutomaticRegistryProvider.cpp" "Discovery/NativeRegistryProvider.cpp" "Discovery/NativeRegistryBatch.cpp" "Papyrus/NativeHostBinding.cpp")
	file(READ "${ROOT}/src/${ADMISSION}" ADMISSION_SOURCE)
	string(FIND "${ADMISSION_SOURCE}" "HasNativeFacadeContract(" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Admission bypasses loaded facade contract: ${ADMISSION}")
	endif()
endforeach()
foreach(FACADE SKI_ConfigManager SKI_ConfigBase)
	file(READ "${ROOT}/scripts/Source/host/${FACADE}.psc" SOURCE)
	if(FACADE STREQUAL "SKI_ConfigManager")
		string(FIND "${SOURCE}" "MCMBridgeNative.GetProtocolVersion() != BridgeCallAdmissionContract()" PROTOCOL_GATE)
		string(FIND "${SOURCE}" "MCMBridgeRegistry.Bootstrap(self)" FIRST_OPERATION)
	else()
		string(FIND "${SOURCE}" "MCMBridgeNative.GetProtocolVersion() != 2" PROTOCOL_GATE)
		string(FIND "${SOURCE}" "_bridgeToken = a_token" FIRST_OPERATION)
	endif()
	if(PROTOCOL_GATE EQUAL -1 OR FIRST_OPERATION EQUAL -1 OR PROTOCOL_GATE GREATER FIRST_OPERATION)
		message(FATAL_ERROR "${FACADE} must reject an incompatible DLL protocol before host activation")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeManagerFunctions.cpp" MANAGER_BINDING)
file(READ "${ROOT}/src/Papyrus/NativeManagerBatch.cpp" REGISTRATION_QUEUE)
foreach(REQUIRED "requests.Claim(request.session, request.id)" "registry.RegisterBatch(menus)" "registry.Owns(claimed.front()->manager)" "seen.insert(batch[end].menu.object.get()).second" "batch[end].session == batch[start].session")
	string(FIND "${REGISTRATION_QUEUE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing grouped registration admission: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Discovery/NativeRegistryBatch.cpp" BATCH_PROVIDER)
string(FIND "${BATCH_PROVIDER}" "BuildNativeRegistryMirror(" BUILD_MIRROR)
string(FIND "${BATCH_PROVIDER}" "registry.RegisterBatch(" COMMIT_REGISTRY)
string(FIND "${BATCH_PROVIDER}" "Install(view," INSTALL_MIRROR)
if(BUILD_MIRROR EQUAL -1 OR COMMIT_REGISTRY LESS BUILD_MIRROR OR INSTALL_MIRROR LESS COMMIT_REGISTRY)
	message(FATAL_ERROR "Grouped registration must validate mirrors before committing and install before returning")
endif()
if(NOT MANAGER_BINDING MATCHES "return bootstrap && reset && registration && removal && results && cancellation;" OR MANAGER_BINDING MATCHES "a_vm->RegisterFunction")
	message(FATAL_ERROR "Native manager admission must require every transport binding")
endif()
file(READ "${ROOT}/src/Plugin/Plugin.cpp" PLUGIN_ADMISSION)
string(FIND "${PLUGIN_ADMISSION}" "Native manager transport is incomplete; MCM Bridge remains inactive" MANAGER_FAILURE)
if(MANAGER_FAILURE EQUAL -1)
	message(FATAL_ERROR "Plugin startup must reject incomplete native manager transport")
endif()
string(SUBSTRING "${PLUGIN_ADMISSION}" ${MANAGER_FAILURE} 200 MANAGER_EXIT)
if(NOT MANAGER_EXIT MATCHES "return false;")
	message(FATAL_ERROR "Manager transport failure must disable the API and reject activation")
endif()
file(READ "${ROOT}/scripts/Source/host/SKI_ConfigBase.psc" PAGE_FACADE)
string(FIND "${PAGE_FACADE}" "if !MCMBridgeNative.AdmitPage(_bridgeToken, a_page, a_index)" PAGE_ADMISSION)
string(FIND "${PAGE_FACADE}" "_currentPage = a_page" PAGE_MUTATION)
if(PAGE_ADMISSION EQUAL -1 OR PAGE_MUTATION LESS PAGE_ADMISSION)
	message(FATAL_ERROR "SetPage must admit the original caller before mutating page state")
endif()
file(READ "${ROOT}/src/Papyrus/NativeFacadeNavigation.cpp" PAGE_GATE)
file(READ "${ROOT}/src/Papyrus/NativeHostBinding.cpp" CALL_BINDING)
string(FIND "${PAGE_FACADE}" "BindNativeHost(MCMBridgeNative.AcquireConfig())" CONFIG_ENTRY)
if(CONFIG_ENTRY EQUAL -1)
	message(FATAL_ERROR "OpenConfig must establish its own facade binding")
endif()
if(CALL_BINDING MATCHES "DispatchMethodCall[^;]*BindNativeHost")
	message(FATAL_ERROR "Opening a host config must not dispatch a separate binding call")
endif()
foreach(REQUIRED [=[GetName() != "OpenConfig"]=] "host.IsActive(*owned)" "pageReady && configReady")
	string(FIND "${PAGE_GATE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing config ownership admission: ${REQUIRED}")
	endif()
endforeach()
foreach(REQUIRED "GetObjectTypeName() != \"SKI_ConfigBase\"" "GetName() != \"SetPage\"" "TokenForOwner(" "ResolveCallbackSession(a_frame)")
	string(FIND "${PAGE_GATE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing direct page ownership guard: ${REQUIRED}")
	endif()
endforeach()
if(PAGE_GATE MATCHES "QueueScriptPage")
	message(FATAL_ERROR "SetPage must execute on its original stack, not hand off a replacement call")
endif()
file(READ "${ROOT}/src/Papyrus/NativeFacadeCalls.cpp" CALL_ADMISSION)
file(READ "${ROOT}/src/Plugin/BridgeControllerScriptCalls.cpp" SCRIPT_CALLS)
foreach(REQUIRED "BeginExternalOperation(owner, lease)" "calls.Enter(" "calls.Leave(" "RetireScriptContext(true)" "WritePauseService::GetSingleton().Begin" "NativeHostUI::AttachScriptStack")
	string(FIND "${SCRIPT_CALLS}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing external facade lifecycle boundary: ${REQUIRED}")
	endif()
endforeach()
foreach(METHOD OpenConfig CloseConfig SetPage SelectOption ResetOption HighlightOption RequestSliderDialogData RequestMenuDialogData RequestColorDialogData RequestInputDialogData SetSliderValue SetMenuIndex SetColorValue SetInputText RemapKey)
	if(NOT PAGE_FACADE MATCHES "function ${METHOD}\\([^\n]*\\)\n\tint admission = BridgeEnterCall\\(\\)")
		message(FATAL_ERROR "Unprotected facade entry point: ${METHOD}")
	endif()
endforeach()
file(READ "${ROOT}/src/Plugin/BridgeControllerHosted.cpp" HOSTED_DRIVE)
string(FIND "${HOSTED_DRIVE}" "hostedPageID == pageID && viewLoad.Ready(modID, pageID)" CURRENT_VIEW_GATE)
if(CURRENT_VIEW_GATE EQUAL -1)
	message(FATAL_ERROR "Hosted reuse must require the current view activation")
endif()
file(READ "${ROOT}/src/Plugin/BridgeControllerNativeNavigation.cpp" NATIVE_NAVIGATION)
if(NATIVE_NAVIGATION MATCHES "CreateSession|Dispatch|ClassicScanOperation")
	message(FATAL_ERROR "Registered native navigation must not create execution sessions or dispatch callbacks")
endif()
foreach(REQUIRED "ReadRegisteredNavigation(" "FinishScan(session)")
	string(FIND "${NATIVE_NAVIGATION}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing native registered-navigation boundary: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeExternalPage.cpp" EXTERNAL_PAGE)
foreach(REQUIRED "GetName() != \"ForcePageListReset\"" "GetParamCount() != 1" "caller->GetPageForFrame()).IsBool()" "configPanel.setPageNames")
	string(FIND "${EXTERNAL_PAGE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing external navigation guard: ${REQUIRED}")
	endif()
endforeach()
foreach(REQUIRED "GetName() != \"GoToPage\"" "GetName() == \"_RenameModule\"" "GetObjectTypeName() != \"nl_mcm\"" "GetParamCount() != (rename ? 2U : 1U)" "replacement.IsString()" "page.IsString()" "ReadIdentity(token)" "CaptureScriptView(identity->modID)" "ResolveIdentity(script)" "QueueScriptPage(identity.session, revision")
	string(FIND "${EXTERNAL_PAGE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing external page handoff guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeExternalState.cpp" EXTERNAL_STATE)
foreach(REQUIRED "GetObjectTypeName() != \"nl_mcm\"" "FunctionType::kGetter" "GetParamCount() != 0" "properties[index].name == \"IsMCMOpen\"" "properties[index].info.getFunction == function" "TokenForOwner(" "IsActive(token)")
	string(FIND "${EXTERNAL_STATE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing external state-query guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeExternalClose.cpp" EXTERNAL_CLOSE)
foreach(REQUIRED "GetName() != \"CloseMCM\"" "GetObjectTypeName() != \"nl_mcm\"" "caller->owningFunction->GetParamCount() != 1" "close.IsBool()" "ReadIdentity(token)" "CaptureScriptView(identity->modID)" "ResolveIdentity(script)" "CloseScriptView(identity.session, revision")
	string(FIND "${EXTERNAL_CLOSE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing external close handoff guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Discovery/AutomaticRegistryProvider.cpp" PROVIDER)
file(READ "${ROOT}/include/MCMBridge/Discovery/AutomaticRegistryProvider.h" HEADER)
if(PROVIDER MATCHES "Selected\\(|SelectRegistrySource|unlocked\\.|classic\\.(ReadLive|Read|IsAvailable|IsBusy)\\(" OR HEADER MATCHES "MCMUnlockedRegistryProvider")
	message(FATAL_ERROR "Native startup must not select a legacy registry")
endif()
if(NOT PROVIDER MATCHES "IsHelperHostReady\\(\\)")
	message(FATAL_ERROR "Native admission must require Helper capture readiness")
endif()
file(READ "${ROOT}/src/Discovery/NativeRegistryProvider.cpp" REGISTRY)
if(NOT PROVIDER MATCHES "NativeHostUI::IsReady")
	message(FATAL_ERROR "Native admission must require scoped UI cursor bindings")
endif()
foreach(REQUIRED "HasNativeFacade(object)" "HasNativeFacade(a_menu)" "HasNativeFacade(script)")
	string(FIND "${REGISTRY}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing native facade validation: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeQuickOpen.cpp" QUICK_OPEN)
foreach(REQUIRED "GetObjectTypeName() != \"nl_mcm\"" "GetName() != \"OpenMCM\"" "GetName() != \"OnKeyDown\"" "quick->SetBool(false)" "ResolveIdentity(script)" "NativeFacadeSession().Session() != session" "original->GetParamCount() != 1" "expected == actual")
	string(FIND "${QUICK_OPEN}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing native quick-open guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/UI/MessageDialog.cpp" MESSAGE_WINDOW)
foreach(REQUIRED "FrontendWindow::Create(\"Message\"" "Render, true, 580, 0, false, Cancel" "window->SetOpen(true)" "window->SetOpen(false)" "request->valid && !request->valid()" "a_expected && pending->id != a_expected")
	string(FIND "${MESSAGE_WINDOW}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing independent message-window lifecycle guard: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Framework/FrontendWindow.cpp" FRONTEND_WINDOWS)
file(READ "${ROOT}/src/Framework/FlickApi.cpp" FLICK_WINDOWS)
foreach(REQUIRED "SKSEMenuFramework::AddWindow(callbacks.Get(windows.size()), a_blocking)" "CanRenderAuxiliary" "window->primary" "FlickApi::RegisterWindow(*window)")
	string(FIND "${FRONTEND_WINDOWS}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing independent frontend-window lifecycle guard: ${REQUIRED}")
	endif()
endforeach()
foreach(REQUIRED "CanRenderAuxiliary(Frontend::kFlick)" "window.UserClose()" "RenderContext context(Frontend::kFlick, FlickRichTextRenderer::Draw, true)")
	string(FIND "${FLICK_WINDOWS}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing independent FLICK-window lifecycle guard: ${REQUIRED}")
	endif()
endforeach()
foreach(PAGE_RENDERER BrowserWindow MCMWindow)
	file(READ "${ROOT}/src/UI/${PAGE_RENDERER}.cpp" PAGE_SOURCE)
	if(PAGE_SOURCE MATCHES "MessageDialog::Render")
		message(FATAL_ERROR "Messages must not depend on a selected browser page")
	endif()
endforeach()
file(READ "${ROOT}/src/Framework/FrameworkApi.cpp" FRAMEWORK_SOURCE)
foreach(REQUIRED "MessageDialog::Install()" "MessageDialog::Cancel()")
	string(FIND "${FRAMEWORK_SOURCE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing message-window framework lifecycle: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Papyrus/NativeFacade.cpp" FACADE_BINDINGS)
file(READ "${ROOT}/src/Papyrus/NativeFacadeRuntime.cpp" RUNTIME_BINDINGS)
file(READ "${ROOT}/include/MCMBridge/Papyrus/NativeFacadeBinding.h" CHECKED_BINDING)
if(FACADE_BINDINGS MATCHES "a_vm->RegisterFunction" OR RUNTIME_BINDINGS MATCHES "a_vm->RegisterFunction")
	message(FATAL_ERROR "Facade binding must not discard the VM registration result")
endif()
foreach(REQUIRED "if (!vm.BindNativeMethod(function.get()))" "valid = false" "SetCallableFromTasklets")
	string(FIND "${CHECKED_BINDING}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing checked native binding contract: ${REQUIRED}")
	endif()
endforeach()
foreach(REQUIRED "facadeReady.store(false)" "binding.IsValid() && runtime && navigation" "facadeReady.load() ? 2 : 0")
	string(FIND "${FACADE_BINDINGS}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing complete facade readiness gate: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Plugin/Plugin.cpp" PLUGIN_SOURCE)
foreach(REQUIRED "GetModuleHandleW(L\"MenuMaid2.dll\")" "redone || seeded || menuMaid" "seeded, !unlocked.value_or(false), menuMaid)")
	string(FIND "${PLUGIN_SOURCE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing Menu Maid 2 startup exclusion: ${REQUIRED}")
	endif()
endforeach()
file(READ "${ROOT}/src/Plugin/StartupCompatibility.cpp" STARTUP_DIALOG)
string(FIND "${STARTUP_DIALOG}" "Menu Maid 2 (MenuMaid2.dll)" MENU_MAID_NOTICE)
if(MENU_MAID_NOTICE EQUAL -1)
	message(FATAL_ERROR "Startup conflict dialog must identify Menu Maid 2")
endif()
string(FIND "${PLUGIN_SOURCE}" "if (!IsNativeFacadeReady())" FACADE_GATE)
string(FIND "${PLUGIN_SOURCE}" "if (!RegisterNativeManager(" MANAGER_GATE)
if(FACADE_GATE EQUAL -1 OR MANAGER_GATE EQUAL -1 OR FACADE_GATE GREATER MANAGER_GATE)
	message(FATAL_ERROR "Plugin activation must require facade readiness before manager binding")
endif()
file(READ "${ROOT}/src/Papyrus/NativeHostUI.cpp" UI_BINDINGS)
file(READ "${ROOT}/include/MCMBridge/Papyrus/NativeFacadeFunction.h" FACADE_FUNCTION)
foreach(REQUIRED "ResolveCallbackSession(a_frame)" "owner && !NativeFacadeSession().IsActive(*owner)" "a_name == \"AddOption\" ? -1" "a_name == \"TakeMessage\" ? -2" "Base::MarshallAndDispatch")
	string(FIND "${FACADE_FUNCTION}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing expired callback facade guard: ${REQUIRED}")
	endif()
endforeach()
string(FIND "${CHECKED_BINDING}" "new NativeFacadeFunction(a_name, a_function)" GUARDED_BINDING)
if(GUARDED_BINDING EQUAL -1)
	message(FATAL_ERROR "Every facade binding must use callback expiry admission")
endif()
string(FIND "${UI_BINDINGS}" "integers && numbers && names && menuState && quickOpen && a_cursorReady" MENU_STATE_GATE)
if(MENU_STATE_GATE EQUAL -1)
	message(FATAL_ERROR "Native admission must include the owned menu-state binding")
endif()
file(READ "${ROOT}/src/Papyrus/NativeHostMenuState.cpp" MENU_STATE)
foreach(REQUIRED "ResolveSession(a_frame, menu.c_str())" "IsActive(*token)" "original->GetIsStatic()" "original->GetParamCount() != 1" "GetIsLatent()" "expected == actual")
	string(FIND "${MENU_STATE}" "${REQUIRED}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "Missing scoped menu-state admission guard: ${REQUIRED}")
	endif()
endforeach()
foreach(OBSOLETE
	include/MCMBridge/Discovery/MCMUnlockedRegistryProvider.h
	src/Discovery/MCMUnlockedRegistryProvider.cpp
	include/MCMBridge/Discovery/UnlockedNativeRegistry.h
	src/Discovery/UnlockedNativeRegistry.cpp
	include/MCMBridge/Core/UnlockedRegistryQuery.h
	src/Core/UnlockedRegistryQuery.cpp
	include/MCMBridge/Core/RegistrySelection.h
	include/MCMBridge/Core/UnlockedVersion.h)
	if(EXISTS "${ROOT}/${OBSOLETE}")
		message(FATAL_ERROR "Obsolete Unlocked registry adapter must not return: ${OBSOLETE}")
	endif()
endforeach()

file(READ "${ROOT}/src/Plugin/JournalRedirect.cpp" REDIRECT)
file(READ "${ROOT}/src/UI/MCMWindow.cpp" MCM_WINDOW)
if(REDIRECT MATCHES "OpenOriginalPanel|NotifyOriginalMCMState|originalMethod|bypass" OR MCM_WINDOW MATCHES "OpenOriginal|Open original")
	message(FATAL_ERROR "Native frontend must not expose original MCM navigation")
endif()
foreach(OBSOLETE include/MCMBridge/UI/OriginalPageNavigator.h src/UI/OriginalPageNavigator.cpp src/Plugin/BridgeControllerNavigation.cpp)
	if(EXISTS "${ROOT}/${OBSOLETE}")
		message(FATAL_ERROR "Obsolete original MCM navigation must not return: ${OBSOLETE}")
	endif()
endforeach()

file(READ "${ROOT}/include/MCMBridge/Plugin/BridgeController.h" CONTROLLER_HEADER)
file(GLOB CONTROLLERS "${ROOT}/src/Plugin/BridgeController*.cpp")
foreach(CONTROLLER IN LISTS CONTROLLERS)
	file(READ "${CONTROLLER}" CONTROLLER_SOURCE)
	if(CONTROLLER_SOURCE MATCHES "IsNativeHost|UsesNative|IsClassicMCMActive|originalMCMOpen|RegistrySettler|registrySettler|PauseScanForOriginalMCM|ScheduleStabilityCheck")
		message(FATAL_ERROR "Controller must execute only the native host: ${CONTROLLER}")
	endif()
endforeach()
if(CONTROLLER_HEADER MATCHES "IsNativeHost|IsClassicMCMActive|originalMCMOpen|nativeHost|RegistrySettler|registrySettler")
	message(FATAL_ERROR "Controller must not retain obsolete host-mode state")
endif()
foreach(OBSOLETE include/MCMBridge/Discovery/ClassicRegistryProvider.h src/Discovery/ClassicRegistryProvider.cpp include/MCMBridge/Core/RegistrySettler.h src/Core/RegistrySettler.cpp)
	if(EXISTS "${ROOT}/${OBSOLETE}")
		message(FATAL_ERROR "Obsolete registry polling must not return: ${OBSOLETE}")
	endif()
endforeach()
