string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef TEST_ID)
set(SOURCE "${ROOT}/config/MCMBridge.ini")
set(DESTINATION "${TEST_OUTPUT}/MCMBridge-defaults-${TEST_ID}.ini")
include("${ROOT}/cmake/CopyDefaultSettings.cmake")
file(SHA256 "${SOURCE}" SOURCE_HASH)
file(SHA256 "${DESTINATION}" DESTINATION_HASH)
if(NOT SOURCE_HASH STREQUAL DESTINATION_HASH)
	message(FATAL_ERROR "Missing settings were not populated from shipped defaults")
endif()

set(CUSTOM_SETTINGS "[General]\nPauseDuringWrites=false\nRedirectMCM=false\n[Other]\nPreserve=value\n")
file(WRITE "${DESTINATION}" "${CUSTOM_SETTINGS}")
include("${ROOT}/cmake/CopyDefaultSettings.cmake")
file(READ "${DESTINATION}" ACTUAL_SETTINGS)
file(REMOVE "${DESTINATION}")
if(NOT ACTUAL_SETTINGS STREQUAL CUSTOM_SETTINGS)
	message(FATAL_ERROR "Deployment modified existing user settings")
endif()
