cmake_minimum_required(VERSION 3.28)
set(FIXTURE "${OUTPUT}/native-package-release-fixture")
file(MAKE_DIRECTORY "${FIXTURE}/native-bootstrap/Seq" "${FIXTURE}/native-scripts")
file(WRITE "${FIXTURE}/Bridge.dll" "test bridge\n")
file(WRITE "${FIXTURE}/native-bootstrap/SkyUI_SE.esp" "test standalone plugin\n")
file(WRITE "${FIXTURE}/native-bootstrap/Seq/SkyUI_SE.seq" "test sequence\n")
foreach(SCRIPT MCMBridgeNative MCMBridgeRegistry SKI_ConfigBase SKI_ConfigManager SKI_QuestBase SKI_PlayerLoadGameAlias)
	file(WRITE "${FIXTURE}/native-scripts/${SCRIPT}.pex" "test script: ${SCRIPT}\n")
endforeach()

set(PREFLIGHT OFF)
function(STAGE VARIANT EXPECT_SUCCESS)
	execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT=${ROOT}" "-DBUILD_ROOT=${FIXTURE}"
		"-DBRIDGE=${FIXTURE}/Bridge.dll" "-DVARIANT=${VARIANT}" "-DPREFLIGHT=${PREFLIGHT}"
		-P "${ROOT}/cmake/StageNativePackage.cmake" RESULT_VARIABLE STATUS OUTPUT_VARIABLE LOG ERROR_VARIABLE ERRORS)
	if(EXPECT_SUCCESS AND NOT STATUS EQUAL 0)
		message(FATAL_ERROR "Package failed: ${LOG}${ERRORS}")
	elseif(NOT EXPECT_SUCCESS AND STATUS EQUAL 0)
		message(FATAL_ERROR "Invalid package request was accepted")
	endif()
endfunction()

foreach(VARIANT skyui standalone)
	STAGE("${VARIANT}" TRUE)
	STAGE("${VARIANT}" TRUE)
	set(PACKAGE "${FIXTURE}/native-packages/${VARIANT}")
	file(SHA256 "${ROOT}/assets/reset.png" ICON_SOURCE)
	file(SHA256 "${PACKAGE}/Interface/MCMBridge/reset.png" ICON_PACKAGED)
	if(NOT ICON_SOURCE STREQUAL ICON_PACKAGED)
		message(FATAL_ERROR "Packaged reset texture changed")
	endif()
	foreach(SCRIPT MCMBridgeNative MCMBridgeRegistry SKI_ConfigBase SKI_ConfigManager)
		file(SHA256 "${FIXTURE}/native-scripts/${SCRIPT}.pex" BEFORE)
		file(SHA256 "${PACKAGE}/Scripts/${SCRIPT}.pex" AFTER)
		if(NOT BEFORE STREQUAL AFTER)
			message(FATAL_ERROR "Packaged script changed: ${SCRIPT}")
		endif()
	endforeach()
	file(GLOB_RECURSE FILES RELATIVE "${PACKAGE}" "${PACKAGE}/*")
	list(LENGTH FILES COUNT)
	if(VARIANT STREQUAL "skyui")
		if(NOT COUNT EQUAL 10 OR EXISTS "${PACKAGE}/SkyUI_SE.esp" OR EXISTS "${PACKAGE}/Scripts/SKI_QuestBase.pex")
			message(FATAL_ERROR "SkyUI package contains extra files or standalone scripts")
		endif()
	else()
		if(NOT COUNT EQUAL 14 OR NOT EXISTS "${PACKAGE}/SkyUI_SE.esp" OR NOT EXISTS "${PACKAGE}/Scripts/SKI_PlayerLoadGameAlias.pex")
			message(FATAL_ERROR "Standalone package is incomplete")
		endif()
	endif()
endforeach()
STAGE("both" FALSE)
set(PREFLIGHT ON)
STAGE("skyui" FALSE)
set(PREFLIGHT OFF)
file(WRITE "${FIXTURE}/native-packages/skyui/unexpected.txt" "synthetic stale package file\n")
STAGE("skyui" FALSE)
file(REMOVE "${FIXTURE}/native-packages/skyui/unexpected.txt")
file(RENAME "${FIXTURE}/native-scripts/SKI_ConfigBase.pex" "${FIXTURE}/native-scripts/SKI_ConfigBase.pex.saved")
STAGE("standalone" FALSE)
file(RENAME "${FIXTURE}/native-scripts/SKI_ConfigBase.pex.saved" "${FIXTURE}/native-scripts/SKI_ConfigBase.pex")
