cmake_minimum_required(VERSION 3.28)
if(DEFINED CANDIDATE)
	set(PROJECT_VERSION "1.1.0")
	set(MCM_BRIDGE_TEST_RC "${CANDIDATE}")
	include("${ROOT}/cmake/TestVersion.cmake")
	if(NOT MCM_BRIDGE_PACKAGE_VERSION STREQUAL EXPECTED)
		message(FATAL_ERROR "Unexpected candidate version: ${MCM_BRIDGE_PACKAGE_VERSION}")
	endif()
	return()
endif()

set(INVALID -1 01 abc 65536)
foreach(CANDIDATE IN ITEMS 0 1 2 65535 -1 01 abc 65536)
	if(CANDIDATE STREQUAL "0")
		set(EXPECTED "1.1.0")
	else()
		set(EXPECTED "1.1.0rc${CANDIDATE}")
	endif()
	execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT=${ROOT}" "-DCANDIDATE=${CANDIDATE}" "-DEXPECTED=${EXPECTED}" -P "${CMAKE_CURRENT_LIST_FILE}"
		RESULT_VARIABLE STATUS OUTPUT_VARIABLE LOG ERROR_VARIABLE ERRORS)
	if(CANDIDATE IN_LIST INVALID)
		if(STATUS EQUAL 0)
			message(FATAL_ERROR "Invalid candidate accepted: ${CANDIDATE}")
		endif()
	elseif(NOT STATUS EQUAL 0)
		message(FATAL_ERROR "Candidate check failed: ${LOG}${ERRORS}")
	endif()
endforeach()
