[General]
PauseDuringWrites=true
CloseJournalOnRedirect=true
PreferFLICK=true
GroupMCMs=false
AlphabeticMCMs=false
MCMRangeEnds=CGLRZ

[FLICK]
; PageSelector: 0 = top panel, 1 = left panel, 2 = dropdown.
PageSelector=1
PageRows=3
; Left panel width as a percentage of the available content area.
PageWidth=25

[Aliases]
