set(CONTENT "#pragma once\n#include <cstdint>\n#include <span>\nnamespace MCMBridge::ShippedScripts {\n")
foreach(SCRIPT IN ITEMS SKI_ConfigManager SKI_ConfigBase MCMBridgeNative MCMBridgeRegistry)
	file(READ "${INPUT}/${SCRIPT}.pex" BYTES HEX)
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${BYTES}")
	string(APPEND CONTENT "inline constexpr std::uint8_t ${SCRIPT}[]{${BYTES}};\n")
endforeach()
string(APPEND CONTENT "struct Script { const char* path; std::span<const std::uint8_t> bytes; };\ninline constexpr Script all[]{\n")
foreach(SCRIPT IN ITEMS SKI_ConfigManager SKI_ConfigBase MCMBridgeNative MCMBridgeRegistry)
	string(APPEND CONTENT "{\"Scripts/${SCRIPT}.pex\", ${SCRIPT}},\n")
endforeach()
string(APPEND CONTENT "};\n}\n")
file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT "${CONTENT}" @ONLY)
