if(NOT IS_DIRECTORY "${SKSE_SCRIPTS}/vanilla" OR NOT IS_DIRECTORY "${SKSE_SCRIPTS}/modified")
	message(FATAL_ERROR "SKSE script sources are required for facade compilation")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
file(GLOB SOURCES RELATIVE "${SKSE_SCRIPTS}/vanilla" "${SKSE_SCRIPTS}/vanilla/*.psc")
file(GLOB ADDITIONS RELATIVE "${SKSE_SCRIPTS}/modified" "${SKSE_SCRIPTS}/modified/*.psc")
list(APPEND SOURCES ${ADDITIONS})
list(REMOVE_DUPLICATES SOURCES)
foreach(SCRIPT IN LISTS SOURCES)
	set(CONTENT "")
	if(EXISTS "${SKSE_SCRIPTS}/vanilla/${SCRIPT}")
		file(READ "${SKSE_SCRIPTS}/vanilla/${SCRIPT}" CONTENT)
	endif()
	if(EXISTS "${SKSE_SCRIPTS}/modified/${SCRIPT}")
		file(READ "${SKSE_SCRIPTS}/modified/${SCRIPT}" EXTENSION)
		string(APPEND CONTENT "\n${EXTENSION}")
	endif()
	file(WRITE "${OUTPUT}/${SCRIPT}" "${CONTENT}")
endforeach()
