cmake_minimum_required(VERSION 3.28)
foreach(REQUIRED ROOT BUILD_SCRIPTS MODE)
	if(NOT DEFINED ${REQUIRED} OR "${${REQUIRED}}" STREQUAL "")
		message(FATAL_ERROR "Missing repository script input: ${REQUIRED}")
	endif()
endforeach()
if(NOT MODE MATCHES "^(stage|refresh)$")
	message(FATAL_ERROR "Unknown repository script mode: ${MODE}")
endif()

set(SCRIPTS MCMBridgeNative MCMBridgeRegistry SKI_ConfigBase SKI_ConfigManager SKI_QuestBase SKI_PlayerLoadGameAlias)
set(FILES)
foreach(SCRIPT IN LISTS SCRIPTS)
	if(SCRIPT STREQUAL "MCMBridgeNative")
		list(APPEND FILES "Source/${SCRIPT}.psc")
	else()
		list(APPEND FILES "Source/host/${SCRIPT}.psc")
	endif()
	list(APPEND FILES "Compiled/${SCRIPT}.pex")
endforeach()

if(MODE STREQUAL "stage")
	file(STRINGS "${ROOT}/Compiled/SHA256.txt" RECORDS)
	set(RECORDED_FILES)
	foreach(RECORD IN LISTS RECORDS)
		if(NOT RECORD MATCHES "^([0-9a-f]+)  (.+)$")
			message(FATAL_ERROR "Malformed repository script checksum: ${RECORD}")
		endif()
		set(HASH "${CMAKE_MATCH_1}")
		set(PATH "${CMAKE_MATCH_2}")
		string(LENGTH "${HASH}" HASH_LENGTH)
		if(NOT HASH_LENGTH EQUAL 64 OR NOT PATH IN_LIST FILES OR PATH IN_LIST RECORDED_FILES)
			message(FATAL_ERROR "Invalid repository script checksum entry: ${PATH}")
		endif()
		list(APPEND RECORDED_FILES "${PATH}")
		set("EXPECTED_${PATH}" "${HASH}")
	endforeach()
	list(LENGTH FILES EXPECTED_COUNT)
	list(LENGTH RECORDED_FILES ACTUAL_COUNT)
	if(NOT EXPECTED_COUNT EQUAL ACTUAL_COUNT)
		message(FATAL_ERROR "Repository script checksums are incomplete")
	endif()
endif()

# Check the complete set before copying. Source checksums use LF text so Git
# checkout line-ending conversion cannot make an unchanged source appear stale.
set(MANIFEST "")
foreach(PATH IN LISTS FILES)
	set(INPUT "${ROOT}/${PATH}")
	if(PATH MATCHES "\\.pex$" AND MODE STREQUAL "refresh")
		get_filename_component(NAME "${PATH}" NAME)
		set(INPUT "${BUILD_SCRIPTS}/${NAME}")
	endif()
	if(PATH MATCHES "\\.psc$")
		file(READ "${INPUT}" CONTENT)
		string(REPLACE "\r\n" "\n" CONTENT "${CONTENT}")
		string(SHA256 HASH "${CONTENT}")
	else()
		file(SHA256 "${INPUT}" HASH)
	endif()
	if(MODE STREQUAL "stage" AND NOT HASH STREQUAL "${EXPECTED_${PATH}}")
		message(FATAL_ERROR "Repository script mismatch: ${PATH}. Recompile sources and run refresh-precompiled-scripts.")
	endif()
	string(APPEND MANIFEST "${HASH}  ${PATH}\n")
endforeach()

foreach(SCRIPT IN LISTS SCRIPTS)
	if(MODE STREQUAL "refresh")
		set(INPUT "${BUILD_SCRIPTS}/${SCRIPT}.pex")
		set(OUTPUT "${ROOT}/Compiled/${SCRIPT}.pex")
	else()
		set(INPUT "${ROOT}/Compiled/${SCRIPT}.pex")
		set(OUTPUT "${BUILD_SCRIPTS}/${SCRIPT}.pex")
	endif()
	get_filename_component(PARENT "${OUTPUT}" DIRECTORY)
	file(MAKE_DIRECTORY "${PARENT}")
	file(COPY_FILE "${INPUT}" "${OUTPUT}" ONLY_IF_DIFFERENT)
endforeach()
if(MODE STREQUAL "refresh")
	file(WRITE "${ROOT}/Compiled/SHA256.txt" "${MANIFEST}")
endif()
message(STATUS "Repository scripts ${MODE}: six matched source/PEX pairs")
