cmake_minimum_required(VERSION 3.28)
foreach(REQUIRED ROOT BUILD_ROOT BRIDGE VARIANT)
	if(NOT DEFINED ${REQUIRED} OR "${${REQUIRED}}" STREQUAL "")
		message(FATAL_ERROR "Missing native package input: ${REQUIRED}")
	endif()
endforeach()
if(NOT DEFINED PREFLIGHT OR PREFLIGHT)
	message(FATAL_ERROR "Native runtime packages require a build with native host preflight disabled")
endif()
if(NOT VARIANT MATCHES "^(skyui|standalone)$")
	message(FATAL_ERROR "Select exactly one bootstrap variant: skyui or standalone")
endif()
file(REAL_PATH "${BUILD_ROOT}" BUILD_ROOT)
set(OUTPUT "${BUILD_ROOT}/native-packages/${VARIANT}")
function(REQUIRE_BUILD_PATH PATH)
	cmake_path(IS_PREFIX BUILD_ROOT "${PATH}" NORMALIZE IS_BUILD_OUTPUT)
	if(NOT IS_BUILD_OUTPUT)
		message(FATAL_ERROR "Native package output must remain inside the build directory")
	endif()
	set(EXISTING "${PATH}")
	while(NOT EXISTS "${EXISTING}" AND NOT IS_SYMLINK "${EXISTING}")
		get_filename_component(EXISTING "${EXISTING}" DIRECTORY)
	endwhile()
	file(REAL_PATH "${EXISTING}" RESOLVED)
	if(NOT RESOLVED STREQUAL EXISTING)
		message(FATAL_ERROR "Native package output must not follow symbolic links: ${PATH}")
	endif()
endfunction()
REQUIRE_BUILD_PATH("${OUTPUT}")

set(SOURCES "${BRIDGE}" "${ROOT}/config/MCMBridge.ini" "${ROOT}/assets/reset.png"
	"${ROOT}/LICENSE" "${ROOT}/THIRD_PARTY_NOTICES.md" "${ROOT}/licenses/MinHook.txt")
set(DESTINATIONS "SKSE/Plugins/MCMBridge.dll" "SKSE/Plugins/MCMBridge.ini" "Interface/MCMBridge/reset.png"
	"licenses/MCMBridge/LICENSE" "licenses/MCMBridge/THIRD_PARTY_NOTICES.md" "licenses/MCMBridge/MinHook.txt")
set(SCRIPTS MCMBridgeNative MCMBridgeRegistry SKI_ConfigBase SKI_ConfigManager)
if(VARIANT STREQUAL "standalone")
	list(APPEND SCRIPTS SKI_QuestBase SKI_PlayerLoadGameAlias)
	list(APPEND SOURCES "${BUILD_ROOT}/native-bootstrap/SkyUI_SE.esp" "${BUILD_ROOT}/native-bootstrap/Seq/SkyUI_SE.seq")
	list(APPEND DESTINATIONS SkyUI_SE.esp Seq/SkyUI_SE.seq)
endif()
foreach(SCRIPT IN LISTS SCRIPTS)
	list(APPEND SOURCES "${BUILD_ROOT}/native-scripts/${SCRIPT}.pex")
	list(APPEND DESTINATIONS "Scripts/${SCRIPT}.pex")
endforeach()

foreach(SOURCE IN LISTS SOURCES)
	if(NOT EXISTS "${SOURCE}" OR IS_DIRECTORY "${SOURCE}")
		message(FATAL_ERROR "Missing required native runtime file: ${SOURCE}")
	endif()
endforeach()
file(GLOB_RECURSE EXISTING_FILES RELATIVE "${OUTPUT}" "${OUTPUT}/*")
foreach(FILE IN LISTS EXISTING_FILES)
	if(NOT FILE IN_LIST DESTINATIONS)
		message(FATAL_ERROR "Unexpected file in native package output: ${FILE}; use a clean build output")
	endif()
endforeach()

list(LENGTH SOURCES COUNT)
math(EXPR LAST "${COUNT} - 1")
set(MANIFEST "variant=${VARIANT}\n")
foreach(INDEX RANGE ${LAST})
	list(GET SOURCES ${INDEX} SOURCE)
	list(GET DESTINATIONS ${INDEX} RELATIVE)
	set(DESTINATION "${OUTPUT}/${RELATIVE}")
	REQUIRE_BUILD_PATH("${DESTINATION}")
	file(SHA256 "${SOURCE}" BEFORE_HASH)
	get_filename_component(PARENT "${DESTINATION}" DIRECTORY)
	file(MAKE_DIRECTORY "${PARENT}")
	file(COPY_FILE "${SOURCE}" "${DESTINATION}" ONLY_IF_DIFFERENT)
	file(SHA256 "${DESTINATION}" COPIED_HASH)
	file(SHA256 "${SOURCE}" AFTER_HASH)
	if(NOT BEFORE_HASH STREQUAL COPIED_HASH OR NOT BEFORE_HASH STREQUAL AFTER_HASH)
		message(FATAL_ERROR "Native package source changed or copy failed: ${RELATIVE}")
	endif()
	string(APPEND MANIFEST "${COPIED_HASH}  ${RELATIVE}\n")
endforeach()
file(WRITE "${BUILD_ROOT}/native-packages/${VARIANT}-SHA256.txt" "${MANIFEST}")
message(STATUS "Staged ${VARIANT} native package: ${COUNT} Bridge files; no dependencies or game deployment")
