cmake_minimum_required(VERSION 3.28)
foreach(REQUIRED ROOT BUILD_ROOT)
	if(NOT DEFINED ${REQUIRED} OR "${${REQUIRED}}" STREQUAL "")
		message(FATAL_ERROR "Missing release package input: ${REQUIRED}")
	endif()
endforeach()
file(REAL_PATH "${ROOT}" ROOT)
file(REAL_PATH "${BUILD_ROOT}" BUILD_ROOT)
file(READ "${ROOT}/CMakeLists.txt" PROJECT)
if(NOT PROJECT MATCHES "project\\(MCMBridge VERSION ([0-9]+\\.[0-9]+\\.[0-9]+)")
	message(FATAL_ERROR "Missing project version")
endif()
set(VERSION "${CMAKE_MATCH_1}")
file(READ "${ROOT}/vcpkg.json" VCPKG)
string(JSON MANIFEST_VERSION GET "${VCPKG}" version-string)
if(NOT VERSION STREQUAL MANIFEST_VERSION)
	message(FATAL_ERROR "CMake and vcpkg versions differ")
endif()
set(NAME "MCMBridge-${VERSION}.zip")
set(ARCHIVE "${BUILD_ROOT}/packages/${NAME}")
set(EXPECTED LICENSE THIRD_PARTY_NOTICES.md licenses/MCMBridge/MinHook.txt
	SKSE/Plugins/MCMBridge.dll SKSE/Plugins/MCMBridge.ini
	Scripts/MCMBridgeNative.pex Scripts/MCMBridgeRegistry.pex Scripts/SKI_ConfigBase.pex Scripts/SKI_ConfigManager.pex)
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${ARCHIVE}"
	RESULT_VARIABLE STATUS OUTPUT_VARIABLE ENTRIES ERROR_VARIABLE ERRORS)
if(NOT STATUS EQUAL 0)
	message(FATAL_ERROR "Cannot inspect release package: ${ERRORS}")
endif()
string(REPLACE "\r\n" "\n" ENTRIES "${ENTRIES}")
string(REPLACE "\n" ";" ENTRIES "${ENTRIES}")
set(FILES)
foreach(ENTRY IN LISTS ENTRIES)
	if(ENTRY STREQUAL "" OR ENTRY MATCHES "/$")
		continue()
	endif()
	if(NOT ENTRY IN_LIST EXPECTED OR ENTRY IN_LIST FILES)
		message(FATAL_ERROR "Unexpected release package entry: ${ENTRY}")
	endif()
	list(APPEND FILES "${ENTRY}")
endforeach()
list(SORT FILES)
list(SORT EXPECTED)
if(NOT FILES STREQUAL EXPECTED)
	message(FATAL_ERROR "Incomplete release package: ${FILES}")
endif()

# Inspect bytes from the archive, not a separate staging directory. The allowlist
# above rejects extra files and path traversal before extraction.
set(EXTRACTED "${BUILD_ROOT}/release-package-check")
file(MAKE_DIRECTORY "${EXTRACTED}")
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE}" DESTINATION "${EXTRACTED}")
foreach(ENTRY IN LISTS FILES)
	if(ENTRY STREQUAL "SKSE/Plugins/MCMBridge.dll")
		set(SOURCE "${BUILD_ROOT}/Release/MCMBridge.dll")
	elseif(ENTRY STREQUAL "SKSE/Plugins/MCMBridge.ini")
		set(SOURCE "${ROOT}/config/MCMBridge.ini")
	elseif(ENTRY STREQUAL "licenses/MCMBridge/MinHook.txt")
		set(SOURCE "${ROOT}/licenses/MinHook.txt")
	elseif(ENTRY MATCHES "^Scripts/(.+)$")
		set(SOURCE "${ROOT}/scripts/Compiled/${CMAKE_MATCH_1}")
	else()
		set(SOURCE "${ROOT}/${ENTRY}")
	endif()
	file(SHA256 "${SOURCE}" SOURCE_HASH)
	file(SHA256 "${EXTRACTED}/${ENTRY}" PACKAGED_HASH)
	if(NOT SOURCE_HASH STREQUAL PACKAGED_HASH)
		message(FATAL_ERROR "Release package bytes differ: ${ENTRY}")
	endif()
endforeach()
file(SHA256 "${ARCHIVE}" HASH)
file(WRITE "${BUILD_ROOT}/packages/SHA256.txt" "${HASH}  ${NAME}\n")
message(STATUS "Verified ${NAME}: nine runtime/license files, matching repository PEX; SHA256 recorded")
